#!/usr/bin/env python

# A python script to run all tests
# This should eventually be moved into a single python test script that
# automatically discovers tests and runs them as a group, giving a single
# summary about pass/fails. Brandt did this for pycontrol and should be
# able to do it again.

import subprocess as SP
try:
    import mpi4py
    distributed = True
except ImportError:
    distributed = False

SP.call(['clear'])
SP.call(['./testfieldoperations.py'])
SP.call(['./testbpod.py'])
SP.call(['./testpod.py'])
SP.call(['./testdmd.py'])
SP.call(['./testutil.py'])
SP.call(['./testera.py'])
SP.call(['./testbpodltirom.py'])

if distributed:
    SP.call(['mpiexec','-n','3','python', 'testfieldoperations.py'])
    SP.call(['mpiexec','-n','3','python','testbpod.py'])
    SP.call(['mpiexec','-n','3','python', 'testpod.py'])
    SP.call(['mpiexec','-n','3','python', 'testdmd.py'])
    SP.call(['mpiexec','-n','3','python','testutil.py'])
    # These are serial only right now:
    #mpiexec -n 3 python testera.py
    #mpiexec -n 3 python testbpodltirom.py
